"""Canonical operational resource units for JWIS (issue #25).

Every resource quantity in the product is derived here, so prediction, permit
intake, optimizer input, API schema and UI labels share one formula and one
meaning. Units are explicit in the names:

- ``crews_required``   crew teams (one team works one 18 t truckload per shift)
- ``workers_required`` people (one team is ``CREW_SIZE_WORKERS`` people)
- ``man_hours_required`` person-hours (``workers x SHIFT_HOURS``)
- ``trucks_required``  trucks (one truck carries ``TRUCK_CAPACITY_TONS`` tons)
- ``bins_required``    large bins (one bin holds ``BIN_CAPACITY_TONS`` tons)

Before this module the same field names carried three different meanings: a
"crew" was one truck's worth of tonnage in the forecast pipeline and four
people in the permit pipeline, so identical tonnage produced crew counts that
differed by 4x, and ``man_hours_required`` inherited whichever reading its
producer used. Nothing in the API said which was meant.
"""

from __future__ import annotations

from math import ceil

TRUCK_CAPACITY_TONS = 18.0
BIN_CAPACITY_TONS = 2.5
CREW_SIZE_WORKERS = 4
SHIFT_HOURS = 8.0
EVENT_WASTE_KG_PER_PERSON = 1.2  # event crowd waste generation rate

UNIT_GLOSSARY = {
    "trucks_required": "trucks",
    "crews_required": "crew teams (1 team operates 1 truck per shift)",
    "workers_required": "people (crews x 4)",
    "man_hours_required": "person-hours (workers x shift hours)",
    "bins_required": "large bins",
    "recommended_extra_trucks": "additional trucks for demand above baseline",
    "recommended_extra_crews": "additional crew teams",
    "recommended_extra_workers": "additional people",
}


def event_tons_for_attendance(attendance: int) -> float:
    """Waste generated by an event crowd, in tons."""
    return round(max(0, attendance) * EVENT_WASTE_KG_PER_PERSON / 1000.0, 1)


def trucks_for_tons(tons: float, minimum: int = 0) -> int:
    """Trucks needed to move `tons` in one shift."""
    return max(minimum, ceil(max(0.0, tons) / TRUCK_CAPACITY_TONS))


def extra_trucks_for(tons: float, baseline_tons: float) -> int:
    """Additional trucks needed for the tonnage above the baseline."""
    return trucks_for_tons(max(0.0, tons - baseline_tons))


def bins_for_tons(tons: float) -> int:
    return max(0, ceil(max(0.0, tons) / BIN_CAPACITY_TONS))


def workers_for_crews(crews: int) -> int:
    return crews * CREW_SIZE_WORKERS


def person_hours_for_workers(workers: int) -> float:
    return workers * SHIFT_HOURS


def resource_requirements(tons: float, baseline_tons: float | None = None) -> dict:
    """The one resource block every producer emits.

    `tons` is the total demand for the period. `baseline_tons` (when given)
    additionally yields the marginal fleet recommendation, measured against the
    same baseline the spike percentage uses — not against a different one.
    """
    crews = trucks_for_tons(tons, minimum=1 if tons > 0 else 0)
    workers = workers_for_crews(crews)
    block = {
        "trucks_required": crews,
        "crews_required": crews,
        "workers_required": workers,
        "man_hours_required": person_hours_for_workers(workers),
        "bins_required": bins_for_tons(tons),
        "units": dict(UNIT_GLOSSARY),
    }
    if baseline_tons is not None:
        extra = extra_trucks_for(tons, baseline_tons)
        block["recommended_extra_trucks"] = extra
        block["recommended_extra_crews"] = extra
        block["recommended_extra_workers"] = workers_for_crews(extra)
    return block


def resource_basis() -> str:
    """Human-readable basis, generated so it cannot drift from the constants."""
    return (
        f"canonical units: 1 truck = {TRUCK_CAPACITY_TONS:g} t, "
        f"1 crew = {CREW_SIZE_WORKERS} workers per truck, "
        f"1 shift = {SHIFT_HOURS:g} h, 1 bin = {BIN_CAPACITY_TONS:g} t; "
        "man_hours_required is person-hours (workers x shift hours)"
    )
